// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbLlUeFN9aQW36T9aJdMIs-5J5ZGq9WRc',
    appId: '1:611179071521:web:1c2bc30b9d93b3ae4f3b60',
    messagingSenderId: '611179071521',
    projectId: 'flicknestfirebase',
    authDomain: 'flicknestfirebase.firebaseapp.com',
    databaseURL: 'https://flicknestfirebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flicknestfirebase.firebasestorage.app',
    measurementId: 'G-CZXZ9LDXZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZDIAksIA_CbHqYyzuCP2KzqV_lSARrOc',
    appId: '1:611179071521:android:d5d07edbfcb6e2f14f3b60',
    messagingSenderId: '611179071521',
    projectId: 'flicknestfirebase',
    databaseURL: 'https://flicknestfirebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flicknestfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWU7ydI0eFd39U3LA_V3396dKV_HdKQuU',
    appId: '1:611179071521:ios:afdea81cbb93bd364f3b60',
    messagingSenderId: '611179071521',
    projectId: 'flicknestfirebase',
    databaseURL: 'https://flicknestfirebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flicknestfirebase.firebasestorage.app',
    iosBundleId: 'com.example.flicknestFlutterFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWU7ydI0eFd39U3LA_V3396dKV_HdKQuU',
    appId: '1:611179071521:ios:afdea81cbb93bd364f3b60',
    messagingSenderId: '611179071521',
    projectId: 'flicknestfirebase',
    databaseURL: 'https://flicknestfirebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flicknestfirebase.firebasestorage.app',
    iosBundleId: 'com.example.flicknestFlutterFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbLlUeFN9aQW36T9aJdMIs-5J5ZGq9WRc',
    appId: '1:611179071521:web:356a849b1a8697654f3b60',
    messagingSenderId: '611179071521',
    projectId: 'flicknestfirebase',
    authDomain: 'flicknestfirebase.firebaseapp.com',
    databaseURL: 'https://flicknestfirebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flicknestfirebase.firebasestorage.app',
    measurementId: 'G-8CDMYZXP49',
  );
}
